apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-service
  name: demo-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: demo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-service
  name: demo-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      volumes:
        - name: credentials
          secret:
            secretName: demo-service-account
      containers:
        - name: demo-service
          image: gcr.io/qwiklabs-gcp-02-cbf7d4831ec7/demo-service
          volumeMounts:
            - name: credentials
              mountPath: "/etc/credentials"
              readOnly: true
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/credentials/service-account.json
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
